"use client";

import { pick, type Locale } from "../lib/i18n";

export function createDesktopShellCopy(locale: Locale) {
  return {
    title: pick(locale, "K-ERA Desktop Workspace", "K-ERA 데스크톱 워크스페이스"),
    subtitle: pick(
      locale,
      "Set up the local data folder, hospital connection, and sign-in for this PC.",
      "이 PC에서 사용할 데이터 폴더, 병원 연결 정보, 로그인만 설정하면 됩니다.",
    ),
    openSettings: pick(locale, "Setup", "설정"),
    closeSettings: pick(locale, "Hide setup", "설정 닫기"),
    startRuntime: pick(locale, "Start app services", "앱 서비스 시작"),
    startingRuntime: pick(locale, "Starting app services...", "앱 서비스 시작 중..."),
    refreshingRuntime: pick(locale, "Refreshing status...", "상태 새로고침 중..."),
    stopRuntime: pick(locale, "Stop app services", "앱 서비스 중지"),
    stoppingRuntime: pick(locale, "Stopping app services...", "앱 서비스 중지 중..."),
    refreshRuntime: pick(locale, "Refresh status", "상태 새로고침"),
    saveSettings: pick(locale, "Save and continue", "저장하고 계속"),
    savingSettings: pick(locale, "Saving...", "저장 중..."),
    resetSettings: pick(locale, "Reset setup", "설정 초기화"),
    username: pick(locale, "Username", "아이디"),
    password: pick(locale, "Password", "비밀번호"),
    googleSignIn: pick(locale, "Sign in with Google", "Google로 로그인"),
    signIn: pick(locale, "Sign in and open workspace", "로그인하고 워크스페이스 열기"),
    signingIn: pick(locale, "Signing in...", "로그인 중..."),
    devSignIn: pick(locale, "Dev admin login", "개발용 관리자 로그인"),
    loginFailed: pick(locale, "Login failed.", "로그인에 실패했습니다."),
    runtimeFailed: pick(
      locale,
      "The desktop app could not start its local services.",
      "데스크톱 앱의 로컬 서비스를 시작하지 못했습니다.",
    ),
    storageDir: pick(locale, "Data folder", "데이터 폴더"),
    storageDirHint: pick(
      locale,
      "Choose where this PC should store SQLite, images, models, and logs.",
      "이 PC의 SQLite, 이미지, 모델, 로그를 저장할 폴더를 선택하세요.",
    ),
    browseStorageDir: pick(locale, "Browse", "찾아보기"),
    browseStorageDirTitle: pick(locale, "Choose data folder", "데이터 폴더 선택"),
    controlPlaneUrl: pick(locale, "Hospital server URL", "병원 서버 주소"),
    controlPlaneUrlHint: pick(
      locale,
      "Enter the server address provided for this hospital or site.",
      "이 병원 또는 사이트에 대해 받은 서버 주소를 입력하세요.",
    ),
    nodeId: pick(locale, "This PC ID", "이 PC ID"),
    nodeIdHint: pick(
      locale,
      "Use the PC ID provided during setup. It identifies this desktop in the hospital network.",
      "초기 설정 때 받은 PC ID를 입력하세요. 병원 네트워크에서 이 데스크톱을 구분하는 값입니다.",
    ),
    nodeToken: pick(locale, "Connection key", "연결 키"),
    nodeTokenHint: pick(
      locale,
      "Use the connection key provided for this PC.",
      "이 PC에 대해 받은 연결 키를 입력하세요.",
    ),
    siteId: pick(locale, "Default hospital code", "기본 병원 코드"),
    siteIdHint: pick(
      locale,
      "Enter the hospital code that should open by default after sign-in.",
      "로그인 후 기본으로 열 병원 코드를 입력하세요.",
    ),
    pythonPath: pick(locale, "Python path override", "Python 경로 직접 지정"),
    pythonPathHint: pick(
      locale,
      "Leave this empty unless support asked you to change it.",
      "지원 담당자가 요청한 경우가 아니면 비워 두세요.",
    ),
    managedBackend: pick(locale, "App-managed service", "앱이 직접 시작"),
    externalBackend: pick(locale, "Use an external service", "외부 서비스 사용"),
    sidecarTransport: pick(locale, "Built-in AI service", "내장 AI 서비스"),
    httpTransport: pick(locale, "External AI service", "외부 AI 서비스"),
    sessionBusy: pick(locale, "Opening saved session...", "저장된 세션을 여는 중..."),
    sessionBlocked: pick(
      locale,
      "This desktop app opens only approved local workspace accounts. Use the web admin app for access requests and central operations.",
      "이 데스크톱 앱은 승인된 로컬 워크스페이스 계정만 엽니다. 접근 요청과 중앙 운영은 웹 관리자 앱에서 진행하세요.",
    ),
    signOut: pick(locale, "Sign out", "로그아웃"),
    runtimeStatus: pick(locale, "App status", "앱 상태"),
    appStatusDescription: pick(
      locale,
      "You only need the basic setup below. Technical details stay hidden unless you open them.",
      "아래 기본 설정만 입력하면 됩니다. 기술 정보는 필요할 때만 열어보세요.",
    ),
    configPath: pick(locale, "Config file", "설정 파일"),
    backendUrl: pick(locale, "App server", "앱 서버"),
    backendHealthy: pick(locale, "App server status", "앱 서버 상태"),
    workerRunning: pick(locale, "Background jobs", "백그라운드 작업"),
    runtimeNotReady: pick(
      locale,
      "Finish the basic setup first, then start the app services.",
      "먼저 기본 설정을 마친 뒤 앱 서비스를 시작하세요.",
    ),
    runtimeMode: pick(locale, "Install mode", "설치 모드"),
    backendSource: pick(locale, "App files", "앱 파일 위치"),
    envSource: pick(locale, "Settings source", "설정 읽기 위치"),
    resourceDir: pick(locale, "Bundled app files", "번들 앱 파일"),
    runtimeDir: pick(locale, "Runtime directory", "실행 폴더"),
    logsDir: pick(locale, "Logs directory", "로그 디렉터리"),
    runtimeErrors: pick(locale, "Runtime errors", "런타임 오류"),
    runtimeWarnings: pick(locale, "Runtime warnings", "런타임 경고"),
    runtimeLookupDetails: pick(locale, "Technical details", "기술 정보"),
    backendCandidates: pick(locale, "App file search paths", "앱 파일 탐색 경로"),
    pythonCandidates: pick(locale, "Python search paths", "Python 탐색 경로"),
    openConfigFile: pick(locale, "Open config", "설정 열기"),
    openAppData: pick(locale, "Open app data", "앱 데이터 열기"),
    openRuntimeLogs: pick(locale, "Open logs", "로그 열기"),
    openResources: pick(locale, "Open resources", "리소스 열기"),
    openStorage: pick(locale, "Open storage", "저장소 열기"),
    runtimeReady: pick(locale, "Installation check", "설치 점검"),
    setupChecklistTitle: pick(locale, "First-time setup", "처음 실행 설정"),
    setupChecklistDescription: pick(
      locale,
      "Most users only need three things: a data folder, the hospital connection, and a login.",
      "대부분의 사용자는 데이터 폴더, 병원 연결 정보, 로그인만 준비하면 됩니다.",
    ),
    guidedSetupTitle: pick(locale, "Guided setup", "안내 설정"),
    guidedSetupDescription: pick(
      locale,
      "Follow the steps below once for this PC, then you can sign in normally.",
      "이 PC에서 아래 단계를 한 번만 완료하면 이후에는 바로 로그인해서 사용할 수 있습니다.",
    ),
    setupProgress: pick(locale, "Setup progress", "설정 진행도"),
    nextAction: pick(locale, "Next action", "다음 작업"),
    openSettingsAction: pick(locale, "Open setup form", "설정 입력 열기"),
    signInStepReady: pick(
      locale,
      "Setup is complete. Use the sign-in form below.",
      "설정이 끝났습니다. 아래 로그인으로 진행하세요.",
    ),
    runtimeServicesTitle: pick(locale, "App services", "앱 서비스"),
    backendService: pick(locale, "App server", "앱 서버"),
    workerService: pick(locale, "Background worker", "백그라운드 작업"),
    mlService: pick(locale, "AI service", "AI 서비스"),
    readyState: pick(locale, "Ready", "준비됨"),
    attentionState: pick(locale, "Needs attention", "확인 필요"),
    optionalState: pick(locale, "Not required", "필수 아님"),
    currentStepState: pick(locale, "Current", "현재 단계"),
    pendingStepState: pick(locale, "Pending", "대기"),
    doneStepState: pick(locale, "Done", "완료"),
    requiredSettingsTitle: pick(locale, "1. Basic setup", "1. 기본 설정"),
    advancedSettingsTitle: pick(locale, "Advanced options", "고급 옵션"),
    advancedSettingsToggle: pick(locale, "Open advanced options", "고급 옵션 열기"),
    supportPathsTitle: pick(locale, "Troubleshooting", "문제 해결"),
    troubleshootingToggle: pick(locale, "Open troubleshooting tools", "문제 해결 도구 열기"),
    supportPathsDescription: pick(
      locale,
      "Use these only when something is broken or support asks for them.",
      "앱에 문제가 있거나 지원 담당자가 요청할 때만 사용하세요.",
    ),
    requiredSettingsDescription: pick(
      locale,
      "Most users only need these fields.",
      "대부분의 사용자는 아래 항목만 입력하면 됩니다.",
    ),
    advancedSettingsDescription: pick(
      locale,
      "Leave these alone unless support asked you to change them.",
      "지원 담당자가 요청한 경우가 아니라면 그대로 두세요.",
    ),
    loginSectionTitle: pick(locale, "2. Sign in", "2. 로그인"),
    loginSectionDescription: pick(
      locale,
      "Researchers sign in with Google. Admin and site admin accounts can still use passwords after setup is complete.",
      "설정이 끝나면 승인된 로컬 워크스페이스 계정으로 로그인하세요.",
    ),
    selfCheckTitle: pick(locale, "Automatic checks", "자동 점검"),
    selfCheckDescription: pick(
      locale,
      "The desktop app verifies storage, databases, hospital connectivity, and model readiness automatically.",
      "데스크톱 앱이 저장소, 데이터베이스, 병원 서버 연결, 모델 준비 상태를 자동으로 점검합니다.",
    ),
    refreshChecks: pick(locale, "Refresh checks", "점검 다시 실행"),
    checksReady: pick(locale, "All critical checks passed.", "핵심 점검을 모두 통과했습니다."),
    checksBlocked: pick(
      locale,
      "One or more critical checks need attention.",
      "핵심 점검 중 확인이 필요한 항목이 있습니다.",
    ),
    passCheck: pick(locale, "Pass", "정상"),
    warnCheck: pick(locale, "Review", "확인 필요"),
    failCheck: pick(locale, "Fail", "실패"),
    exportSupportBundle: pick(locale, "Export support bundle", "지원 파일 내보내기"),
    exportingSupportBundle: pick(locale, "Exporting support bundle...", "지원 파일 내보내는 중..."),
    supportBundleDescription: pick(
      locale,
      "Create a single ZIP file with logs and runtime diagnostics for support.",
      "로그와 런타임 진단 정보를 ZIP 한 파일로 내보냅니다.",
    ),
    supportBundleReady: pick(locale, "Support bundle saved.", "지원 파일을 저장했습니다."),
    openExportedBundle: pick(locale, "Open exported bundle", "내보낸 파일 열기"),
    openPath: pick(locale, "Open path", "경로 열기"),
    updateTitle: pick(locale, "Desktop updates", "데스크톱 업데이트"),
    updateDescription: pick(
      locale,
      "Check whether a newer desktop build is available for this PC.",
      "이 PC에서 사용할 새 데스크톱 빌드가 있는지 확인합니다.",
    ),
    checkUpdates: pick(locale, "Check for updates", "업데이트 확인"),
    checkingUpdates: pick(locale, "Checking for updates...", "업데이트 확인 중..."),
    installUpdate: pick(locale, "Install update", "업데이트 설치"),
    installingUpdate: pick(locale, "Installing update...", "업데이트 설치 중..."),
    noUpdateAvailable: pick(locale, "This desktop build is up to date.", "현재 데스크톱 빌드는 최신입니다."),
    updateAvailable: pick(locale, "A newer desktop build is available.", "새 데스크톱 빌드가 있습니다."),
    updateDownload: pick(locale, "Download release", "릴리스 다운로드"),
    updateInstallReady: pick(
      locale,
      "Automatic installation is available for this update.",
      "이 업데이트는 자동 설치를 지원합니다.",
    ),
    updateInstallManual: pick(
      locale,
      "Automatic installation is unavailable for this release. Open the download page instead.",
      "이 릴리스는 자동 설치를 지원하지 않습니다. 다운로드 페이지를 여세요.",
    ),
    updateInstalled: pick(
      locale,
      "Update package downloaded. Installation will continue automatically.",
      "업데이트 패키지를 내려받았습니다. 설치가 자동으로 계속됩니다.",
    ),
    updateRestartRequired: pick(
      locale,
      "Update installed. Restart the desktop app to finish applying it.",
      "업데이트를 설치했습니다. 적용을 마치려면 데스크톱 앱을 다시 시작하세요.",
    ),
    updateProgress: pick(locale, "Update progress", "업데이트 진행 상태"),
    desktopRuntimeEyebrow: pick(locale, "Desktop runtime", "데스크톱 런타임"),
    runtimeReadyLabel: pick(locale, "Ready", "준비됨"),
    runtimeNotReadyLabel: pick(locale, "Not ready", "미준비"),
    runtimeRunningLabel: pick(locale, "Running", "실행 중"),
    runtimeStoppedLabel: pick(locale, "Stopped", "중지됨"),
    packagedLabel: pick(locale, "Packaged", "설치형"),
    devLabel: pick(locale, "Dev", "개발"),
    blockedLabel: pick(locale, "Blocked", "차단됨"),
    appServiceModeLabel: pick(locale, "App service mode", "앱 서비스 모드"),
    aiServiceModeLabel: pick(locale, "AI service mode", "AI 서비스 모드"),
    updateCheckHint: pick(
      locale,
      "Run the update check to load release information.",
      "업데이트 정보를 보려면 확인을 실행하세요.",
    ),
    noPythonCandidatesResolved: pick(locale, "No Python candidates resolved.", "파이썬 후보가 없습니다."),
    openingSessionTitle: pick(locale, "Opening session", "세션 여는 중"),
    workspaceAccessRequiredTitle: pick(locale, "Workspace access required", "워크스페이스 접근 필요"),
  };
}

export type DesktopShellCopy = ReturnType<typeof createDesktopShellCopy>;
