param(
    [Parameter(Mandatory = $true)]
    [string]$ControlPlaneDatabaseUrl,
    [Parameter(Mandatory = $true)]
    [string]$StorageDir,
    [Parameter(Mandatory = $true)]
    [string]$SharedRoot,
    [Parameter(Mandatory = $true)]
    [string]$CaseReferenceSalt,
    [string]$OutputPath = "",
    [string]$GoogleClientId = "",
    [string]$HiraApiKey = "",
    [string]$OneDriveTenantId = "",
    [string]$OneDriveClientId = "",
    [string]$OneDriveClientSecret = "",
    [string]$OneDriveDriveId = "",
    [string]$OneDriveRootPath = "",
    [ValidateSet("download_url", "local_path")]
    [string]$ModelDistributionMode = "download_url",
    [string]$ModelSourceProvider = "",
    [string]$ApiSecret = "",
    [string]$PatientReferenceSalt = "",
    [switch]$SkipDirectoryCreation
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot ".env.local"
}

function Resolve-FullPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue
    )

    $expanded = [Environment]::ExpandEnvironmentVariables($PathValue)
    return [System.IO.Path]::GetFullPath($expanded)
}

function Convert-ToSqliteUrl {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ResolvedPath
    )

    $normalized = $ResolvedPath -replace "\\", "/"
    return "sqlite:///$normalized/kera.db"
}

function New-RandomHex {
    param([int]$ByteCount = 32)

    $bytes = New-Object byte[] $ByteCount
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
}

function Read-EnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue
    )

    $values = [ordered]@{}
    if (-not (Test-Path $PathValue)) {
        return $values
    }

    foreach ($rawLine in Get-Content $PathValue) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith("#")) {
            continue
        }
        $parts = $line -split "=", 2
        if ($parts.Length -ne 2) {
            continue
        }
        $key = $parts[0].Trim()
        if (-not $key) {
            continue
        }
        $values[$key] = $parts[1]
    }

    return $values
}

function Set-EnvValue {
    param(
        [Parameter(Mandatory = $true)]
        [System.Collections.IDictionary]$Values,
        [Parameter(Mandatory = $true)]
        [string]$Key,
        [string]$Value
    )

    if ($null -eq $Value) {
        return
    }
    $Values[$Key] = $Value
}

function Write-EnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue,
        [Parameter(Mandatory = $true)]
        [System.Collections.IDictionary]$Values
    )

    $knownOrder = @(
        "KERA_API_SECRET",
        "KERA_CASE_REFERENCE_SALT",
        "KERA_PATIENT_REFERENCE_SALT",
        "KERA_GOOGLE_CLIENT_ID",
        "NEXT_PUBLIC_GOOGLE_CLIENT_ID",
        "KERA_HIRA_API_KEY",
        "KERA_ONEDRIVE_TENANT_ID",
        "KERA_ONEDRIVE_CLIENT_ID",
        "KERA_ONEDRIVE_CLIENT_SECRET",
        "KERA_ONEDRIVE_DRIVE_ID",
        "KERA_ONEDRIVE_ROOT_PATH",
        "KERA_CONTROL_PLANE_DATABASE_URL",
        "KERA_DATA_PLANE_DATABASE_URL",
        "KERA_STORAGE_DIR",
        "KERA_CONTROL_PLANE_DIR",
        "KERA_CONTROL_PLANE_ARTIFACT_DIR",
        "KERA_MODEL_DIR",
        "KERA_MODEL_SOURCE_PROVIDER",
        "KERA_MODEL_AUTO_DOWNLOAD",
        "KERA_MODEL_KEEP_VERSIONS",
        "KERA_MODEL_DOWNLOAD_TIMEOUT_SECONDS",
        "KERA_MODEL_DISTRIBUTION_MODE"
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by scripts/configure_local_node.ps1")
    $lines.Add("# Review and add any remaining site-specific secrets if needed.")
    $lines.Add("")

    $written = New-Object System.Collections.Generic.HashSet[string]
    foreach ($key in $knownOrder) {
        if ($Values.Keys -contains $key) {
            $lines.Add("$key=$($Values[$key])")
            $null = $written.Add($key)
        }
    }

    $extraKeys = @($Values.Keys | Where-Object { -not $written.Contains($_) } | Sort-Object)
    if ($extraKeys.Count -gt 0) {
        $lines.Add("")
        $lines.Add("# Existing additional settings")
        foreach ($key in $extraKeys) {
            $lines.Add("$key=$($Values[$key])")
        }
    }

    Set-Content -Path $PathValue -Value $lines -Encoding UTF8
}

$resolvedOutputPath = Resolve-FullPath -PathValue $OutputPath
$resolvedStorageDir = Resolve-FullPath -PathValue $StorageDir
$resolvedSharedRoot = Resolve-FullPath -PathValue $SharedRoot
$resolvedControlPlaneDir = Join-Path $resolvedSharedRoot "control_plane"
$resolvedArtifactDir = Join-Path $resolvedControlPlaneDir "artifacts"
$resolvedModelDir = Join-Path $resolvedSharedRoot "models"
$resolvedDataPlaneDatabaseUrl = Convert-ToSqliteUrl -ResolvedPath $resolvedStorageDir

if (-not $SkipDirectoryCreation) {
    foreach ($pathToCreate in @($resolvedStorageDir, $resolvedControlPlaneDir, $resolvedArtifactDir, $resolvedModelDir)) {
        New-Item -ItemType Directory -Force -Path $pathToCreate | Out-Null
    }
}

$envValues = Read-EnvFile -PathValue $resolvedOutputPath

$effectiveApiSecret = $ApiSecret.Trim()
if (-not $effectiveApiSecret) {
    $effectiveApiSecret = [string]($envValues["KERA_API_SECRET"])
}
if (-not $effectiveApiSecret) {
    $effectiveApiSecret = New-RandomHex
}

$effectiveModelSourceProvider = $ModelSourceProvider.Trim()
if (-not $effectiveModelSourceProvider) {
    if ($ModelDistributionMode -eq "download_url") {
        $effectiveModelSourceProvider = "onedrive_sharepoint"
    } else {
        $effectiveModelSourceProvider = "local"
    }
}

$effectivePatientReferenceSalt = $PatientReferenceSalt.Trim()
if (-not $effectivePatientReferenceSalt) {
    $effectivePatientReferenceSalt = [string]($envValues["KERA_PATIENT_REFERENCE_SALT"])
}
if (-not $effectivePatientReferenceSalt) {
    $effectivePatientReferenceSalt = $CaseReferenceSalt
}

$effectiveOneDriveRootPath = $OneDriveRootPath.Trim()
if (-not $effectiveOneDriveRootPath -and $ModelDistributionMode -eq "download_url") {
    $effectiveOneDriveRootPath = Split-Path -Leaf $resolvedSharedRoot
}

Set-EnvValue -Values $envValues -Key "KERA_API_SECRET" -Value $effectiveApiSecret
Set-EnvValue -Values $envValues -Key "KERA_CASE_REFERENCE_SALT" -Value $CaseReferenceSalt
Set-EnvValue -Values $envValues -Key "KERA_PATIENT_REFERENCE_SALT" -Value $effectivePatientReferenceSalt
Set-EnvValue -Values $envValues -Key "KERA_CONTROL_PLANE_DATABASE_URL" -Value $ControlPlaneDatabaseUrl
Set-EnvValue -Values $envValues -Key "KERA_DATA_PLANE_DATABASE_URL" -Value $resolvedDataPlaneDatabaseUrl
Set-EnvValue -Values $envValues -Key "KERA_STORAGE_DIR" -Value $resolvedStorageDir
Set-EnvValue -Values $envValues -Key "KERA_CONTROL_PLANE_DIR" -Value $resolvedControlPlaneDir
Set-EnvValue -Values $envValues -Key "KERA_CONTROL_PLANE_ARTIFACT_DIR" -Value $resolvedArtifactDir
Set-EnvValue -Values $envValues -Key "KERA_MODEL_DIR" -Value $resolvedModelDir
Set-EnvValue -Values $envValues -Key "KERA_MODEL_SOURCE_PROVIDER" -Value $effectiveModelSourceProvider
Set-EnvValue -Values $envValues -Key "KERA_MODEL_AUTO_DOWNLOAD" -Value "true"
Set-EnvValue -Values $envValues -Key "KERA_MODEL_KEEP_VERSIONS" -Value "2"
Set-EnvValue -Values $envValues -Key "KERA_MODEL_DOWNLOAD_TIMEOUT_SECONDS" -Value "300"
Set-EnvValue -Values $envValues -Key "KERA_MODEL_DISTRIBUTION_MODE" -Value $ModelDistributionMode

if ($GoogleClientId.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_GOOGLE_CLIENT_ID" -Value $GoogleClientId.Trim()
    Set-EnvValue -Values $envValues -Key "NEXT_PUBLIC_GOOGLE_CLIENT_ID" -Value $GoogleClientId.Trim()
}
if ($HiraApiKey.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_HIRA_API_KEY" -Value $HiraApiKey.Trim()
}
if ($OneDriveTenantId.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_ONEDRIVE_TENANT_ID" -Value $OneDriveTenantId.Trim()
}
if ($OneDriveClientId.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_ONEDRIVE_CLIENT_ID" -Value $OneDriveClientId.Trim()
}
if ($OneDriveClientSecret.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_ONEDRIVE_CLIENT_SECRET" -Value $OneDriveClientSecret.Trim()
}
if ($OneDriveDriveId.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_ONEDRIVE_DRIVE_ID" -Value $OneDriveDriveId.Trim()
}
if ($effectiveOneDriveRootPath) {
    Set-EnvValue -Values $envValues -Key "KERA_ONEDRIVE_ROOT_PATH" -Value $effectiveOneDriveRootPath
}

Write-EnvFile -PathValue $resolvedOutputPath -Values $envValues

Write-Host "[K-ERA] Local node configuration updated." -ForegroundColor Green
Write-Host "  Output: $resolvedOutputPath"
Write-Host "  Control plane DB: $ControlPlaneDatabaseUrl"
Write-Host "  Data plane DB: $resolvedDataPlaneDatabaseUrl"
Write-Host "  Shared root: $resolvedSharedRoot"
Write-Host "  Artifact dir: $resolvedArtifactDir"
Write-Host "  Model dir: $resolvedModelDir"
Write-Host "  Distribution mode: $ModelDistributionMode"
