param(
    [Parameter(Mandatory = $true)]
    [string]$ControlPlaneDatabaseUrl,
    [string]$GoogleClientId = "",
    [string]$ApiBaseUrl = "",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot ".env.local"
}

function Resolve-FullPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue
    )

    $expanded = [Environment]::ExpandEnvironmentVariables($PathValue)
    return [System.IO.Path]::GetFullPath($expanded)
}

function Read-EnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue
    )

    $values = [ordered]@{}
    if (-not (Test-Path $PathValue)) {
        return $values
    }

    foreach ($rawLine in Get-Content -Path $PathValue -Encoding UTF8) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith("#")) {
            continue
        }

        $parts = $line -split "=", 2
        if ($parts.Length -ne 2) {
            continue
        }

        $key = $parts[0].Trim()
        if (-not $key) {
            continue
        }

        $values[$key] = $parts[1]
    }

    return $values
}

function Set-EnvValue {
    param(
        [Parameter(Mandatory = $true)]
        [System.Collections.IDictionary]$Values,
        [Parameter(Mandatory = $true)]
        [string]$Key,
        [string]$Value
    )

    if ($null -eq $Value) {
        return
    }
    $Values[$Key] = $Value
}

function Remove-EnvValue {
    param(
        [Parameter(Mandatory = $true)]
        [System.Collections.IDictionary]$Values,
        [Parameter(Mandatory = $true)]
        [string]$Key
    )

    if ($Values.Contains($Key)) {
        $Values.Remove($Key)
    }
}

function Write-EnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue,
        [Parameter(Mandatory = $true)]
        [System.Collections.IDictionary]$Values
    )

    $knownOrder = @(
        "KERA_CONTROL_PLANE_DATABASE_URL",
        "KERA_INTERNAL_API_BASE_URL",
        "KERA_GOOGLE_CLIENT_ID",
        "NEXT_PUBLIC_GOOGLE_CLIENT_ID"
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by scripts/configure_shared_control_plane_client.ps1")
    $lines.Add("# Shares admin/users/projects/sites from one central control-plane DB.")
    $lines.Add("")

    $written = New-Object System.Collections.Generic.HashSet[string]
    foreach ($key in $knownOrder) {
        if ($Values.Keys -contains $key) {
            $lines.Add("$key=$($Values[$key])")
            $null = $written.Add($key)
        }
    }

    $extraKeys = @($Values.Keys | Where-Object { -not $written.Contains($_) } | Sort-Object)
    if ($extraKeys.Count -gt 0) {
        $lines.Add("")
        $lines.Add("# Existing additional settings")
        foreach ($key in $extraKeys) {
            $lines.Add("$key=$($Values[$key])")
        }
    }

    Set-Content -Path $PathValue -Value $lines -Encoding UTF8
}

$resolvedOutputPath = Resolve-FullPath -PathValue $OutputPath
$envValues = Read-EnvFile -PathValue $resolvedOutputPath

Set-EnvValue -Values $envValues -Key "KERA_CONTROL_PLANE_DATABASE_URL" -Value $ControlPlaneDatabaseUrl.Trim()

if ($GoogleClientId.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_GOOGLE_CLIENT_ID" -Value $GoogleClientId.Trim()
    Set-EnvValue -Values $envValues -Key "NEXT_PUBLIC_GOOGLE_CLIENT_ID" -Value $GoogleClientId.Trim()
}

if ($ApiBaseUrl.Trim()) {
    Set-EnvValue -Values $envValues -Key "KERA_INTERNAL_API_BASE_URL" -Value $ApiBaseUrl.Trim().TrimEnd("/")
}

# Avoid accidentally overriding the explicit shared control-plane DB with legacy single-DB settings.
Remove-EnvValue -Values $envValues -Key "KERA_DATABASE_URL"
Remove-EnvValue -Values $envValues -Key "DATABASE_URL"

Write-EnvFile -PathValue $resolvedOutputPath -Values $envValues

Write-Host "[K-ERA] Shared control-plane client configuration updated." -ForegroundColor Green
Write-Host "  Output: $resolvedOutputPath"
Write-Host "  Control plane DB: $ControlPlaneDatabaseUrl"
if ($ApiBaseUrl.Trim()) {
    Write-Host "  Shared API: $($ApiBaseUrl.Trim().TrimEnd('/'))"
}
